### ISSUE TITLE
Exception on node.send(null) from contrib node.

### ISSUE THREAD

**Issue by colinl** [phoddie/node-red-mcu#88]
If a contrib node tries to send a null message then an exception is generated, such as
/home/user/Projects/node-red-mcu/nodered.js (290) # Break: Node.prototype.send: cannot coerce null to object!

This is a not unusual strategy in nodes when it is desired to send nothing.  Well I use it at least.

**Comment by phoddie** [comment]
I didn't imagine someone would send a null message. ;) I've updated the Compatibility node to allow that, both for `node.send()` and the `send` argument passed to the input handler.

**Comment by colinl** [comment]
Working perfectly for me now. Thanks.
